//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthStatus
    {
        public AuthStatus()
        {
            this.UserAuthorizations = new HashSet<UserAuthorization>();
        }
    
        public string AuthStatusId { get; set; }
        public string AuthStatusText { get; set; }
    
        public virtual ICollection<UserAuthorization> UserAuthorizations { get; set; }
    }
}
