//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GenerationLogBookEntities : DbContext
    {
        public GenerationLogBookEntities()
            : base("name=GenerationLogBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthStatus> AuthStatuses { get; set; }
        public virtual DbSet<KPIMaster> KPIMasters { get; set; }
        public virtual DbSet<KPIRegister> KPIRegisters { get; set; }
        public virtual DbSet<ModuleAuthMaster> ModuleAuthMasters { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<MonthlyWorkHoursRegister> MonthlyWorkHoursRegisters { get; set; }
        public virtual DbSet<ReportList> ReportLists { get; set; }
        public virtual DbSet<SiteSafetyRegister> SiteSafetyRegisters { get; set; }
        public virtual DbSet<SitesMaster> SitesMasters { get; set; }
        public virtual DbSet<TemperatureRegister> TemperatureRegisters { get; set; }
        public virtual DbSet<UnitReadingRegister1> UnitReadingRegister1 { get; set; }
        public virtual DbSet<UnitReadingRegister2> UnitReadingRegister2 { get; set; }
        public virtual DbSet<UnitReadingRegister3> UnitReadingRegister3 { get; set; }
        public virtual DbSet<UnitsMaster> UnitsMasters { get; set; }
        public virtual DbSet<UserAuthorization> UserAuthorizations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatus> UserStatuses { get; set; }
        public virtual DbSet<xEmailReminderRecipient> xEmailReminderRecipients { get; set; }
        public virtual DbSet<xEmailReminderRecipientsForNotification> xEmailReminderRecipientsForNotifications { get; set; }
        public virtual DbSet<SiteSafetyRegisterHistorian> SiteSafetyRegisterHistorians { get; set; }
        public virtual DbSet<UnitReadingRegister1Historian> UnitReadingRegister1Historian { get; set; }
        public virtual DbSet<UnitReadingRegister2Historian> UnitReadingRegister2Historian { get; set; }
        public virtual DbSet<UnitReadingRegister3Historian> UnitReadingRegister3Historian { get; set; }
        public virtual DbSet<VMenuMaster> VMenuMasters { get; set; }
        public virtual DbSet<VMonthYear> VMonthYears { get; set; }
        public virtual DbSet<VRPTDaily_KGTPS_Final> VRPTDaily_KGTPS_Final { get; set; }
        public virtual DbSet<VRPTDaily_KGTPS_Station_Final> VRPTDaily_KGTPS_Station_Final { get; set; }
        public virtual DbSet<VRPTDaily_SGTPS_Final> VRPTDaily_SGTPS_Final { get; set; }
        public virtual DbSet<VRPTDaily_SGTPS_Station_Final> VRPTDaily_SGTPS_Station_Final { get; set; }
        public virtual DbSet<VRPTDailyBQPS2_StationwiseFinal> VRPTDailyBQPS2_StationwiseFinal { get; set; }
        public virtual DbSet<VRPTDailyKPC_StationFinal> VRPTDailyKPC_StationFinal { get; set; }
        public virtual DbSet<VRPTDailyKPC_UnitWiseFinal> VRPTDailyKPC_UnitWiseFinal { get; set; }
        public virtual DbSet<VRPTDailySitewiseKPCFinal> VRPTDailySitewiseKPCFinals { get; set; }
        public virtual DbSet<VRPTDailySitewiseReg1CFinal> VRPTDailySitewiseReg1CFinal { get; set; }
        public virtual DbSet<VRPTDailyUnitwiseBQPS2_Stationwise_A> VRPTDailyUnitwiseBQPS2_Stationwise_A { get; set; }
        public virtual DbSet<VRPTDailyUnitwiseFinal> VRPTDailyUnitwiseFinals { get; set; }
        public virtual DbSet<VRPTDailyUnitwiseReg1AFinal> VRPTDailyUnitwiseReg1AFinal { get; set; }
        public virtual DbSet<VRPTDailyUnitwiseReg1CFinal> VRPTDailyUnitwiseReg1CFinal { get; set; }
        public virtual DbSet<VRPTDailyUnitwiseReg1DFinal> VRPTDailyUnitwiseReg1DFinal { get; set; }
        public virtual DbSet<VRPTDailyUnitwiseReg3Final> VRPTDailyUnitwiseReg3Final { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC1> VRPTHourlySitewiseKPC1 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC10> VRPTHourlySitewiseKPC10 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC2> VRPTHourlySitewiseKPC2 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC3> VRPTHourlySitewiseKPC3 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC4> VRPTHourlySitewiseKPC4 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC5> VRPTHourlySitewiseKPC5 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC6> VRPTHourlySitewiseKPC6 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC7> VRPTHourlySitewiseKPC7 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC8> VRPTHourlySitewiseKPC8 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPC9> VRPTHourlySitewiseKPC9 { get; set; }
        public virtual DbSet<VRPTHourlySitewiseKPCFinal> VRPTHourlySitewiseKPCFinals { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1A_1> VRPTHourlyUnitwiseReg1A_1 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1A_2> VRPTHourlyUnitwiseReg1A_2 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1A_3> VRPTHourlyUnitwiseReg1A_3 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1A_4> VRPTHourlyUnitwiseReg1A_4 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1A_5> VRPTHourlyUnitwiseReg1A_5 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1A_6> VRPTHourlyUnitwiseReg1A_6 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1AFinal> VRPTHourlyUnitwiseReg1AFinal { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1AFinal_updated> VRPTHourlyUnitwiseReg1AFinal_updated { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1B_1> VRPTHourlyUnitwiseReg1B_1 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1BFinal> VRPTHourlyUnitwiseReg1BFinal { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1C_1> VRPTHourlyUnitwiseReg1C_1 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1CFinal> VRPTHourlyUnitwiseReg1CFinal { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1cFinal_updated> VRPTHourlyUnitwiseReg1cFinal_updated { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1D_1> VRPTHourlyUnitwiseReg1D_1 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1D_2> VRPTHourlyUnitwiseReg1D_2 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1D_3> VRPTHourlyUnitwiseReg1D_3 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1D_4> VRPTHourlyUnitwiseReg1D_4 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1D_5> VRPTHourlyUnitwiseReg1D_5 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg1DFinal> VRPTHourlyUnitwiseReg1DFinal { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg2_1> VRPTHourlyUnitwiseReg2_1 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg2_2> VRPTHourlyUnitwiseReg2_2 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg2_3> VRPTHourlyUnitwiseReg2_3 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg2Final> VRPTHourlyUnitwiseReg2Final { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg3_1> VRPTHourlyUnitwiseReg3_1 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg3_2> VRPTHourlyUnitwiseReg3_2 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg3_3> VRPTHourlyUnitwiseReg3_3 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg3_4> VRPTHourlyUnitwiseReg3_4 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg3_5> VRPTHourlyUnitwiseReg3_5 { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg3Final> VRPTHourlyUnitwiseReg3Final { get; set; }
        public virtual DbSet<VRPTHourlyUnitwiseReg3Final_update> VRPTHourlyUnitwiseReg3Final_update { get; set; }
        public virtual DbSet<VRPTMonthly_KGTPS_StationFinal> VRPTMonthly_KGTPS_StationFinal { get; set; }
        public virtual DbSet<VRPTMonthly_KGTPS_UnitWiseFinal> VRPTMonthly_KGTPS_UnitWiseFinal { get; set; }
        public virtual DbSet<VRPTMonthly_SGTPS_StationFinal> VRPTMonthly_SGTPS_StationFinal { get; set; }
        public virtual DbSet<VRPTMonthly_SGTPS_UnitWiseFinal> VRPTMonthly_SGTPS_UnitWiseFinal { get; set; }
        public virtual DbSet<VRPTMonthlyKPC_StationFinal> VRPTMonthlyKPC_StationFinal { get; set; }
        public virtual DbSet<VRPTMonthlyKPC_UnitWiseFinal> VRPTMonthlyKPC_UnitWiseFinal { get; set; }
        public virtual DbSet<VRPTMonthlySitewiseBQPS2_Final> VRPTMonthlySitewiseBQPS2_Final { get; set; }
        public virtual DbSet<VRPTMonthlySitewiseReg1CFinal> VRPTMonthlySitewiseReg1CFinal { get; set; }
        public virtual DbSet<VRPTMonthlyUnitwiseBQPS2_A> VRPTMonthlyUnitwiseBQPS2_A { get; set; }
        public virtual DbSet<VRPTMonthlyUnitwiseBQPS2_Final> VRPTMonthlyUnitwiseBQPS2_Final { get; set; }
        public virtual DbSet<VRPTMonthlyUnitwiseReg1CFinal> VRPTMonthlyUnitwiseReg1CFinal { get; set; }
        public virtual DbSet<VRPTMonthlyUnitwiseReg3Final> VRPTMonthlyUnitwiseReg3Final { get; set; }
        public virtual DbSet<VUnitReadingRegister1> VUnitReadingRegister1 { get; set; }
        public virtual DbSet<VUnitReadingRegister2> VUnitReadingRegister2 { get; set; }
        public virtual DbSet<VUnitReadingRegister3> VUnitReadingRegister3 { get; set; }
    
        [DbFunction("GenerationLogBookEntities", "fDaysInMonth")]
        public virtual IQueryable<fDaysInMonth_Result> fDaysInMonth(string month, string year)
        {
            var monthParameter = month != null ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDaysInMonth_Result>("[GenerationLogBookEntities].[fDaysInMonth](@month, @year)", monthParameter, yearParameter);
        }
    
        [DbFunction("GenerationLogBookEntities", "fnSplit")]
        public virtual IQueryable<fnSplit_Result> fnSplit(string @string, string delimiter, string tC)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            var tCParameter = tC != null ?
                new ObjectParameter("TC", tC) :
                new ObjectParameter("TC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnSplit_Result>("[GenerationLogBookEntities].[fnSplit](@String, @Delimiter, @TC)", stringParameter, delimiterParameter, tCParameter);
        }
    
        [DbFunction("GenerationLogBookEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[GenerationLogBookEntities].[Split](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<FetchKPIRegister_Result> FetchKPIRegister(string pSiteId, Nullable<System.DateTime> pMonthYear)
        {
            var pSiteIdParameter = pSiteId != null ?
                new ObjectParameter("pSiteId", pSiteId) :
                new ObjectParameter("pSiteId", typeof(string));
    
            var pMonthYearParameter = pMonthYear.HasValue ?
                new ObjectParameter("pMonthYear", pMonthYear) :
                new ObjectParameter("pMonthYear", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchKPIRegister_Result>("FetchKPIRegister", pSiteIdParameter, pMonthYearParameter);
        }
    
        public virtual ObjectResult<FetchRegister1_Result> FetchRegister1(string pUnitId, Nullable<System.DateTime> pDate)
        {
            var pUnitIdParameter = pUnitId != null ?
                new ObjectParameter("pUnitId", pUnitId) :
                new ObjectParameter("pUnitId", typeof(string));
    
            var pDateParameter = pDate.HasValue ?
                new ObjectParameter("pDate", pDate) :
                new ObjectParameter("pDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchRegister1_Result>("FetchRegister1", pUnitIdParameter, pDateParameter);
        }
    
        public virtual ObjectResult<FetchRegister2_Result> FetchRegister2(string pUnitId, Nullable<System.DateTime> pDate)
        {
            var pUnitIdParameter = pUnitId != null ?
                new ObjectParameter("pUnitId", pUnitId) :
                new ObjectParameter("pUnitId", typeof(string));
    
            var pDateParameter = pDate.HasValue ?
                new ObjectParameter("pDate", pDate) :
                new ObjectParameter("pDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchRegister2_Result>("FetchRegister2", pUnitIdParameter, pDateParameter);
        }
    
        public virtual ObjectResult<FetchRegister3_Result> FetchRegister3(string pUnitId, Nullable<System.DateTime> pDate)
        {
            var pUnitIdParameter = pUnitId != null ?
                new ObjectParameter("pUnitId", pUnitId) :
                new ObjectParameter("pUnitId", typeof(string));
    
            var pDateParameter = pDate.HasValue ?
                new ObjectParameter("pDate", pDate) :
                new ObjectParameter("pDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchRegister3_Result>("FetchRegister3", pUnitIdParameter, pDateParameter);
        }
    
        public virtual ObjectResult<FetchSafetyRegister_Result> FetchSafetyRegister(string pSiteId, Nullable<System.DateTime> pMonthYear)
        {
            var pSiteIdParameter = pSiteId != null ?
                new ObjectParameter("pSiteId", pSiteId) :
                new ObjectParameter("pSiteId", typeof(string));
    
            var pMonthYearParameter = pMonthYear.HasValue ?
                new ObjectParameter("pMonthYear", pMonthYear) :
                new ObjectParameter("pMonthYear", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchSafetyRegister_Result>("FetchSafetyRegister", pSiteIdParameter, pMonthYearParameter);
        }
    
        public virtual ObjectResult<FetchTemperatureRegister_Result> FetchTemperatureRegister(string pSiteId, Nullable<System.DateTime> pDate)
        {
            var pSiteIdParameter = pSiteId != null ?
                new ObjectParameter("pSiteId", pSiteId) :
                new ObjectParameter("pSiteId", typeof(string));
    
            var pDateParameter = pDate.HasValue ?
                new ObjectParameter("pDate", pDate) :
                new ObjectParameter("pDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchTemperatureRegister_Result>("FetchTemperatureRegister", pSiteIdParameter, pDateParameter);
        }
    
        public virtual ObjectResult<string> GetGenLogBookPredefinedReasons(string siteId, string unitId)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            var unitIdParameter = unitId != null ?
                new ObjectParameter("UnitId", unitId) :
                new ObjectParameter("UnitId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetGenLogBookPredefinedReasons", siteIdParameter, unitIdParameter);
        }
    
        public virtual ObjectResult<string> GetGenLogBookPredefinedReasonsBySite(string siteId)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetGenLogBookPredefinedReasonsBySite", siteIdParameter);
        }
    
        public virtual ObjectResult<getGenLogBookRecipients_Result> getGenLogBookRecipients()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGenLogBookRecipients_Result>("getGenLogBookRecipients");
        }
    
        public virtual ObjectResult<getGenLogBookRecipientsForNotification_Result> getGenLogBookRecipientsForNotification(string inputSiteID)
        {
            var inputSiteIDParameter = inputSiteID != null ?
                new ObjectParameter("inputSiteID", inputSiteID) :
                new ObjectParameter("inputSiteID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGenLogBookRecipientsForNotification_Result>("getGenLogBookRecipientsForNotification", inputSiteIDParameter);
        }
    
        public virtual int sendGenLogBookNotificationMail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sendGenLogBookNotificationMail");
        }
    }
}
