//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIRegister
    {
        public string KPIId { get; set; }
        public string SiteId { get; set; }
        public System.DateTime theMonth { get; set; }
        public decimal MaxScore { get; set; }
        public decimal Bad { get; set; }
        public decimal Average { get; set; }
        public decimal Good { get; set; }
        public Nullable<decimal> ActualResult { get; set; }
        public Nullable<decimal> AdjustedResult { get; set; }
        public Nullable<decimal> PointAchieved { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeBy { get; set; }
    
        public virtual SitesMaster SitesMaster { get; set; }
    }
}
