//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ModuleAuthMasters = new HashSet<ModuleAuthMaster>();
        }
    
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
    
        public virtual ICollection<ModuleAuthMaster> ModuleAuthMasters { get; set; }
    }
}
