//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyWorkHoursRegister
    {
        public System.DateTime theMonth { get; set; }
        public string SiteId { get; set; }
        public decimal EmpWorkHours { get; set; }
        public decimal OSPWorkHours { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeBy { get; set; }
    
        public virtual SitesMaster SitesMaster { get; set; }
    }
}
