//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportList
    {
        public string ReportId { get; set; }
        public string ReportCategory { get; set; }
        public string ReportName { get; set; }
        public string ReportController { get; set; }
        public string StatusId { get; set; }
        public string ReportType { get; set; }
    }
}
