//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitesMaster
    {
        public SitesMaster()
        {
            this.KPIRegisters = new HashSet<KPIRegister>();
            this.ModuleAuthMasters = new HashSet<ModuleAuthMaster>();
            this.MonthlyWorkHoursRegisters = new HashSet<MonthlyWorkHoursRegister>();
            this.SiteSafetyRegisters = new HashSet<SiteSafetyRegister>();
            this.xEmailReminderRecipients = new HashSet<xEmailReminderRecipient>();
            this.xEmailReminderRecipientsForNotifications = new HashSet<xEmailReminderRecipientsForNotification>();
            this.xEmailReminderRecipients1 = new HashSet<xEmailReminderRecipient>();
            this.TemperatureRegisters = new HashSet<TemperatureRegister>();
            this.UnitReadingRegister1 = new HashSet<UnitReadingRegister1>();
            this.UnitReadingRegister2 = new HashSet<UnitReadingRegister2>();
            this.UnitReadingRegister3 = new HashSet<UnitReadingRegister3>();
            this.UnitsMasters = new HashSet<UnitsMaster>();
        }
    
        public string SiteId { get; set; }
        public string SiteName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeBy { get; set; }
        public string StatusId { get; set; }
    
        public virtual ICollection<KPIRegister> KPIRegisters { get; set; }
        public virtual ICollection<ModuleAuthMaster> ModuleAuthMasters { get; set; }
        public virtual ICollection<MonthlyWorkHoursRegister> MonthlyWorkHoursRegisters { get; set; }
        public virtual ICollection<SiteSafetyRegister> SiteSafetyRegisters { get; set; }
        public virtual ICollection<xEmailReminderRecipient> xEmailReminderRecipients { get; set; }
        public virtual ICollection<xEmailReminderRecipientsForNotification> xEmailReminderRecipientsForNotifications { get; set; }
        public virtual ICollection<xEmailReminderRecipient> xEmailReminderRecipients1 { get; set; }
        public virtual ICollection<TemperatureRegister> TemperatureRegisters { get; set; }
        public virtual ICollection<UnitReadingRegister1> UnitReadingRegister1 { get; set; }
        public virtual ICollection<UnitReadingRegister2> UnitReadingRegister2 { get; set; }
        public virtual ICollection<UnitReadingRegister3> UnitReadingRegister3 { get; set; }
        public virtual ICollection<UnitsMaster> UnitsMasters { get; set; }
    }
}
