//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSafetyRegisterHistorian
    {
        public System.DateTime theDate { get; set; }
        public string SiteId { get; set; }
        public decimal Fatality { get; set; }
        public decimal LTI { get; set; }
        public decimal RWC { get; set; }
        public decimal MTC { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeBy { get; set; }
        public System.DateTime Tstamp { get; set; }
    }
}
