//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemperatureRegister
    {
        public System.DateTime RdgDateTime { get; set; }
        public string UnitId { get; set; }
        public string SiteId { get; set; }
        public Nullable<decimal> AmbTemp { get; set; }
        public Nullable<decimal> SeaWaterTemp { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeBy { get; set; }
    
        public virtual SitesMaster SitesMaster { get; set; }
    }
}
