//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsMaster
    {
        public UnitsMaster()
        {
            this.UnitReadingRegister1 = new HashSet<UnitReadingRegister1>();
            this.UnitReadingRegister2 = new HashSet<UnitReadingRegister2>();
            this.UnitReadingRegister3 = new HashSet<UnitReadingRegister3>();
        }
    
        public string UnitId { get; set; }
        public string UnitName { get; set; }
        public decimal ReferenceCapacity { get; set; }
        public System.DateTime DpndCapDate { get; set; }
        public int CalcFormulaId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeBy { get; set; }
        public string StatusId { get; set; }
        public string SiteId { get; set; }
        public decimal GDC { get; set; }
    
        public virtual SitesMaster SitesMaster { get; set; }
        public virtual ICollection<UnitReadingRegister1> UnitReadingRegister1 { get; set; }
        public virtual ICollection<UnitReadingRegister2> UnitReadingRegister2 { get; set; }
        public virtual ICollection<UnitReadingRegister3> UnitReadingRegister3 { get; set; }
    }
}
