//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitReadingRegister3Historian
    {
        public string UnitId { get; set; }
        public string SiteId { get; set; }
        public System.DateTime RdgDateTime { get; set; }
        public decimal ActualDispatchMW { get; set; }
        public string OutageNature { get; set; }
        public string CalculateDeration { get; set; }
        public string StartShut { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeBy { get; set; }
        public Nullable<System.DateTime> L1ApproveDate { get; set; }
        public string L1ApproveBy { get; set; }
        public Nullable<System.DateTime> L2ApproveDate { get; set; }
        public string L2ApproveBy { get; set; }
        public string L1Approval { get; set; }
        public string L2Approval { get; set; }
        public Nullable<decimal> GDC { get; set; }
        public Nullable<decimal> ReferenceCapacity { get; set; }
        public string L1ApproveAuthId { get; set; }
        public string L2ApproveAuthId { get; set; }
        public string CreateByAuthId { get; set; }
        public System.DateTime Tstamp { get; set; }
    }
}
