//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitReadingRegister2
    {
        public System.DateTime RdgDateTime { get; set; }
        public string UnitId { get; set; }
        public string SiteId { get; set; }
        public decimal E1ActualDispatchMW { get; set; }
        public decimal E2ActualDispatchMW { get; set; }
        public decimal E3ActualDispatchMW { get; set; }
        public decimal E4ActualDispatchMW { get; set; }
        public decimal E5ActualDispatchMW { get; set; }
        public decimal E6ActualDispatchMW { get; set; }
        public decimal E7ActualDispatchMW { get; set; }
        public decimal E8ActualDispatchMW { get; set; }
        public string E1Outage { get; set; }
        public string E2Outage { get; set; }
        public string E3Outage { get; set; }
        public string E4Outage { get; set; }
        public string E5Outage { get; set; }
        public string E6Outage { get; set; }
        public string E7Outage { get; set; }
        public string E8Outage { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ChangeBy { get; set; }
        public Nullable<System.DateTime> L1ApproveDate { get; set; }
        public string L1ApproveBy { get; set; }
        public Nullable<System.DateTime> L2ApproveDate { get; set; }
        public string L2ApproveBy { get; set; }
        public string L1Approval { get; set; }
        public string L2Approval { get; set; }
        public string L1ApproveAuthId { get; set; }
        public string L2ApproveAuthId { get; set; }
        public string CreateByAuthId { get; set; }
    
        public virtual SitesMaster SitesMaster { get; set; }
        public virtual UnitsMaster UnitsMaster { get; set; }
    }
}
