//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMenuMaster
    {
        public string UserId { get; set; }
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string SiteId { get; set; }
        public string SiteName { get; set; }
        public string AuthId { get; set; }
        public string AuthText { get; set; }
        public string AuthTextMenu { get; set; }
        public string ControllerAction { get; set; }
        public string AuthStatusId { get; set; }
    }
}
