//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMonthYear
    {
        public Nullable<System.DateTime> MonthYear { get; set; }
        public string KPIId { get; set; }
        public string KPIText { get; set; }
        public string Prespective { get; set; }
        public string UnitText { get; set; }
        public short SortPrespective { get; set; }
        public short SortKPI { get; set; }
    }
}
