//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTHourlyUnitwiseReg1A_1
    {
        public string UnitId { get; set; }
        public string SiteId { get; set; }
        public Nullable<System.DateTime> CurrRdgDateTime { get; set; }
        public Nullable<System.DateTime> PrevRdgDateTime { get; set; }
        public Nullable<decimal> GDC { get; set; }
        public Nullable<decimal> ReferenceCapacity { get; set; }
        public Nullable<decimal> ActualDispatchMW { get; set; }
        public Nullable<decimal> CurrActualDispatchMW { get; set; }
        public Nullable<decimal> PrevActualDispatchMW { get; set; }
        public Nullable<decimal> AmbTemp { get; set; }
        public Nullable<decimal> AmbPressure { get; set; }
        public Nullable<decimal> SeaWaterTemp { get; set; }
        public string CurrIsPlanned { get; set; }
        public string CurrIsForced { get; set; }
        public string CurrIsLDC { get; set; }
        public string CurrIsGas { get; set; }
        public string CurrIsOutageDeration { get; set; }
        public string CurrStartupRampId { get; set; }
        public string PrevIsOutageDeration { get; set; }
        public string PrevIsForced { get; set; }
        public string PrevIsPlanned { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> AmbDeration { get; set; }
        public Nullable<decimal> PrevAmbDeration { get; set; }
        public Nullable<decimal> ForcedDeration { get; set; }
        public Nullable<decimal> PlannedDeration { get; set; }
        public string L1Approval { get; set; }
        public string L2Approval { get; set; }
        public Nullable<decimal> PlannedOutageHrs { get; set; }
        public Nullable<decimal> UnplannedOutageHrs { get; set; }
        public Nullable<decimal> UnplannedOutageHrsGrid { get; set; }
        public Nullable<decimal> LDCOutageHrs { get; set; }
        public Nullable<decimal> StandbyHrs { get; set; }
        public Nullable<decimal> GasDerationHrs { get; set; }
        public Nullable<decimal> LDCDerationHrs { get; set; }
        public Nullable<decimal> AmbDerationHrs { get; set; }
        public Nullable<decimal> PlannedRampHrs { get; set; }
        public Nullable<decimal> ForcedRampHrs { get; set; }
    }
}
