//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTDailyUnitwiseFinal
    {
        public long Id { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> theDay { get; set; }
        public Nullable<decimal> GDC { get; set; }
        public Nullable<decimal> ReferenceCapacity { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> AmbDeration { get; set; }
        public Nullable<decimal> ForcedDeration { get; set; }
        public Nullable<decimal> PlannedDeration { get; set; }
        public Nullable<decimal> PlannedOutageHrs { get; set; }
        public Nullable<decimal> UnplannedOutageHrs { get; set; }
        public Nullable<decimal> UnplannedOutageHrsGrid { get; set; }
        public Nullable<decimal> LDCOutageHrs { get; set; }
        public Nullable<decimal> StandbyHrs { get; set; }
        public Nullable<decimal> Total1 { get; set; }
        public Nullable<decimal> UnplannedDerationHrs { get; set; }
        public Nullable<decimal> PlannedDerationHrs { get; set; }
        public Nullable<decimal> GasDerationHrs { get; set; }
        public Nullable<decimal> LDCDerationHrs { get; set; }
        public Nullable<decimal> AmbDerationHrs { get; set; }
        public Nullable<decimal> Total2 { get; set; }
        public Nullable<decimal> PlannedRampHrs { get; set; }
        public Nullable<decimal> ForcedRampHrs { get; set; }
        public Nullable<decimal> PlannedOutageMwh { get; set; }
        public Nullable<decimal> ForcedOutageMwh { get; set; }
        public Nullable<decimal> LDCOutageMwh { get; set; }
        public Nullable<decimal> StandbyMwh { get; set; }
        public Nullable<decimal> Total3 { get; set; }
        public Nullable<decimal> PlannedRampMwh { get; set; }
        public Nullable<decimal> ForcedRampMwh { get; set; }
        public Nullable<decimal> ForcedDerationMwh { get; set; }
        public Nullable<decimal> PlannedDerationMwh { get; set; }
        public Nullable<decimal> LDCDerationMwh { get; set; }
        public Nullable<decimal> GasDerationMwh { get; set; }
        public Nullable<decimal> AmbDerationMwh { get; set; }
        public Nullable<decimal> Total4 { get; set; }
        public Nullable<decimal> AvailabilityPercent { get; set; }
        public Nullable<decimal> EUDH { get; set; }
        public Nullable<decimal> EPDH { get; set; }
        public Nullable<decimal> ELRExclGrid { get; set; }
        public Nullable<decimal> ELR { get; set; }
    }
}
