//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTHourlySitewiseKPC9
    {
        public string SiteId { get; set; }
        public System.DateTime CurrRdgDateTime { get; set; }
        public Nullable<System.DateTime> PrevRdgDateTime { get; set; }
        public Nullable<decimal> DaysDifference { get; set; }
        public Nullable<decimal> GT1ActualDispatchMW { get; set; }
        public Nullable<decimal> GT2ActualDispatchMW { get; set; }
        public Nullable<decimal> GT3ActualDispatchMW { get; set; }
        public Nullable<decimal> GT4ActualDispatchMW { get; set; }
        public Nullable<decimal> ST1ActualDispatchMW { get; set; }
        public Nullable<decimal> ST2ActualDispatchMW { get; set; }
        public Nullable<decimal> PH { get; set; }
        public string CurrGT1IsPlanned { get; set; }
        public string PrevGT1IsPlanned { get; set; }
        public string CurrGT2IsPlanned { get; set; }
        public string PrevGT2IsPlanned { get; set; }
        public string CurrGT3IsPlanned { get; set; }
        public string PrevGT3IsPlanned { get; set; }
        public string CurrGT4IsPlanned { get; set; }
        public string PrevGT4IsPlanned { get; set; }
        public string CurrST1IsPlanned { get; set; }
        public string PrevST1IsPlanned { get; set; }
        public string CurrST2IsPlanned { get; set; }
        public string PrevST2IsPlanned { get; set; }
        public string CurrGT1IsForced { get; set; }
        public string PrevGT1IsForced { get; set; }
        public string CurrGT2IsForced { get; set; }
        public string PrevGT2IsForced { get; set; }
        public string CurrGT3IsForced { get; set; }
        public string PrevGT3IsForced { get; set; }
        public string CurrGT4IsForced { get; set; }
        public string PrevGT4IsForced { get; set; }
        public string CurrST1IsForced { get; set; }
        public string PrevST1IsForced { get; set; }
        public string CurrST2IsForced { get; set; }
        public string PrevST2IsForced { get; set; }
        public string CurrGT1IsOutageDeration { get; set; }
        public string PrevGT1IsOutageDeration { get; set; }
        public string CurrGT2IsOutageDeration { get; set; }
        public string PrevGT2IsOutageDeration { get; set; }
        public string CurrGT3IsOutageDeration { get; set; }
        public string PrevGT3IsOutageDeration { get; set; }
        public string CurrGT4IsOutageDeration { get; set; }
        public string PrevGT4IsOutageDeration { get; set; }
        public string CurrST1IsOutageDeration { get; set; }
        public string PrevST1IsOutageDeration { get; set; }
        public string CurrST2IsOutageDeration { get; set; }
        public string PrevST2IsOutageDeration { get; set; }
        public Nullable<decimal> GT1PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT2PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT3PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT4PlannedOutageHrs { get; set; }
        public Nullable<decimal> ST1PlannedOutageHrs { get; set; }
        public Nullable<decimal> ST2PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT1UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT2UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT3UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT4UnplannedOutageHrs { get; set; }
        public Nullable<decimal> ST1UnplannedOutageHrs { get; set; }
        public Nullable<decimal> ST2UnplannedOutageHrs { get; set; }
        public Nullable<decimal> StationDispatch { get; set; }
        public Nullable<decimal> PlannedOutageHrs { get; set; }
        public Nullable<decimal> UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT1ForcedRampMwh { get; set; }
        public Nullable<decimal> GT2ForcedRampMwh { get; set; }
        public Nullable<decimal> GT3ForcedRampMwh { get; set; }
        public Nullable<decimal> GT4ForcedRampMwh { get; set; }
        public Nullable<decimal> ST1ForcedRampMwh { get; set; }
        public Nullable<decimal> ST2ForcedRampMwh { get; set; }
        public Nullable<decimal> GT1PlannedRampMwh { get; set; }
        public Nullable<decimal> GT2PlannedRampMwh { get; set; }
        public Nullable<decimal> GT3PlannedRampMwh { get; set; }
        public Nullable<decimal> GT4PlannedRampMwh { get; set; }
        public Nullable<decimal> ST1PlannedRampMwh { get; set; }
        public Nullable<decimal> ST2PlannedRampMwh { get; set; }
        public Nullable<decimal> AvailabilityPercent { get; set; }
        public Nullable<decimal> GT1ForcedDerationMwh { get; set; }
        public Nullable<decimal> GT2ForcedDerationMwh { get; set; }
        public Nullable<decimal> GT3ForcedDerationMwh { get; set; }
        public Nullable<decimal> GT4ForcedDerationMwh { get; set; }
        public Nullable<decimal> ST1ForcedDerationMwh { get; set; }
        public Nullable<decimal> ST2ForcedDerationMwh { get; set; }
        public Nullable<decimal> GT1EUDH { get; set; }
        public Nullable<decimal> GT2EUDH { get; set; }
        public Nullable<decimal> GT3EUDH { get; set; }
        public Nullable<decimal> GT4EUDH { get; set; }
        public Nullable<decimal> ST1EUDH { get; set; }
        public Nullable<decimal> ST2EUDH { get; set; }
        public Nullable<decimal> GT1EPDH { get; set; }
        public Nullable<decimal> GT2EPDH { get; set; }
        public Nullable<decimal> GT3EPDH { get; set; }
        public Nullable<decimal> GT4EPDH { get; set; }
        public Nullable<decimal> ST1EPDH { get; set; }
        public Nullable<decimal> ST2EPDH { get; set; }
        public Nullable<decimal> LDCOutageHrs { get; set; }
        public Nullable<decimal> StandbyHrs { get; set; }
        public Nullable<decimal> EUDH { get; set; }
        public Nullable<decimal> EPDH { get; set; }
    }
}
