//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTHourlyUnitwiseReg2Final
    {
        public long Id { get; set; }
        public string UnitId { get; set; }
        public string SiteId { get; set; }
        public Nullable<System.DateTime> RdgDateTime { get; set; }
        public decimal E1ActualDispatchMW { get; set; }
        public string E1Outage { get; set; }
        public decimal E2ActualDispatchMW { get; set; }
        public string E2Outage { get; set; }
        public decimal E3ActualDispatchMW { get; set; }
        public string E3Outage { get; set; }
        public decimal E4ActualDispatchMW { get; set; }
        public string E4Outage { get; set; }
        public decimal E5ActualDispatchMW { get; set; }
        public string E5Outage { get; set; }
        public decimal E6ActualDispatchMW { get; set; }
        public string E6Outage { get; set; }
        public decimal E7ActualDispatchMW { get; set; }
        public string E7Outage { get; set; }
        public decimal E8ActualDispatchMW { get; set; }
        public string E8Outage { get; set; }
        public string L1Approval { get; set; }
        public string L2Approval { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> E1ForcedHrs { get; set; }
        public Nullable<decimal> E2ForcedHrs { get; set; }
        public Nullable<decimal> E3ForcedHrs { get; set; }
        public Nullable<decimal> E4ForcedHrs { get; set; }
        public Nullable<decimal> E5ForcedHrs { get; set; }
        public Nullable<decimal> E6ForcedHrs { get; set; }
        public Nullable<decimal> E7ForcedHrs { get; set; }
        public Nullable<decimal> E8ForcedHrs { get; set; }
        public Nullable<decimal> TotalForcedHrs { get; set; }
        public Nullable<decimal> E1PlannedHrs { get; set; }
        public Nullable<decimal> E2PlannedHrs { get; set; }
        public Nullable<decimal> E3PlannedHrs { get; set; }
        public Nullable<decimal> E4PlannedHrs { get; set; }
        public Nullable<decimal> E5PlannedHrs { get; set; }
        public Nullable<decimal> E6PlannedHrs { get; set; }
        public Nullable<decimal> E7PlannedHrs { get; set; }
        public Nullable<decimal> E8PlannedHrs { get; set; }
        public Nullable<decimal> TotalPlannedHrs { get; set; }
        public Nullable<decimal> E1StandbyHrs { get; set; }
        public Nullable<decimal> E2StandbyHrs { get; set; }
        public Nullable<decimal> E3StandbyHrs { get; set; }
        public Nullable<decimal> E4StandbyHrs { get; set; }
        public Nullable<decimal> E5StandbyHrs { get; set; }
        public Nullable<decimal> E6StandbyHrs { get; set; }
        public Nullable<decimal> E7StandbyHrs { get; set; }
        public Nullable<decimal> E8StandbyHrs { get; set; }
        public Nullable<decimal> TotalStandbyHrs { get; set; }
        public Nullable<decimal> E1ForcedHrsGrid { get; set; }
        public Nullable<decimal> E2ForcedHrsGrid { get; set; }
        public Nullable<decimal> E3ForcedHrsGrid { get; set; }
        public Nullable<decimal> E4ForcedHrsGrid { get; set; }
        public Nullable<decimal> E5ForcedHrsGrid { get; set; }
        public Nullable<decimal> E6ForcedHrsGrid { get; set; }
        public Nullable<decimal> E7ForcedHrsGrid { get; set; }
        public Nullable<decimal> E8ForcedHrsGrid { get; set; }
        public Nullable<decimal> TotalForcedHrsGrid { get; set; }
        public Nullable<decimal> E1AvailabilityExclGrid { get; set; }
        public Nullable<decimal> E2AvailabilityExclGrid { get; set; }
        public Nullable<decimal> E3AvailabilityExclGrid { get; set; }
        public Nullable<decimal> E4AvailabilityExclGrid { get; set; }
        public Nullable<decimal> E5AvailabilityExclGrid { get; set; }
        public Nullable<decimal> E6AvailabilityExclGrid { get; set; }
        public Nullable<decimal> E7AvailabilityExclGrid { get; set; }
        public Nullable<decimal> E8AvailabilityExclGrid { get; set; }
        public Nullable<decimal> TotalAvailabilityExclGrid { get; set; }
        public Nullable<decimal> E1ELRExclGrid { get; set; }
        public Nullable<decimal> E2ELRExclGrid { get; set; }
        public Nullable<decimal> E3ELRExclGrid { get; set; }
        public Nullable<decimal> E4ELRExclGrid { get; set; }
        public Nullable<decimal> E5ELRExclGrid { get; set; }
        public Nullable<decimal> E6ELRExclGrid { get; set; }
        public Nullable<decimal> E7ELRExclGrid { get; set; }
        public Nullable<decimal> E8ELRExclGrid { get; set; }
        public Nullable<decimal> TotalELRExclGrid { get; set; }
        public Nullable<decimal> E1ELRIncGrid { get; set; }
        public Nullable<decimal> E2ELRIncGrid { get; set; }
        public Nullable<decimal> E3ELRIncGrid { get; set; }
        public Nullable<decimal> E4ELRIncGrid { get; set; }
        public Nullable<decimal> E5ELRIncGrid { get; set; }
        public Nullable<decimal> E6ELRIncGrid { get; set; }
        public Nullable<decimal> E7ELRIncGrid { get; set; }
        public Nullable<decimal> E8ELRIncGrid { get; set; }
        public Nullable<decimal> TotalELRIncGrid { get; set; }
    }
}
