//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTHourlySitewiseKPC5
    {
        public string SiteId { get; set; }
        public System.DateTime CurrRdgDateTime { get; set; }
        public Nullable<System.DateTime> PrevRdgDateTime { get; set; }
        public Nullable<decimal> DaysDifference { get; set; }
        public Nullable<decimal> GT1ActualDispatchMW { get; set; }
        public Nullable<decimal> GT2ActualDispatchMW { get; set; }
        public Nullable<decimal> GT3ActualDispatchMW { get; set; }
        public Nullable<decimal> GT4ActualDispatchMW { get; set; }
        public Nullable<decimal> ST1ActualDispatchMW { get; set; }
        public Nullable<decimal> ST2ActualDispatchMW { get; set; }
        public Nullable<decimal> PH { get; set; }
        public string CurrGT1IsPlanned { get; set; }
        public string PrevGT1IsPlanned { get; set; }
        public string CurrGT2IsPlanned { get; set; }
        public string PrevGT2IsPlanned { get; set; }
        public string CurrGT3IsPlanned { get; set; }
        public string PrevGT3IsPlanned { get; set; }
        public string CurrGT4IsPlanned { get; set; }
        public string PrevGT4IsPlanned { get; set; }
        public string CurrST1IsPlanned { get; set; }
        public string PrevST1IsPlanned { get; set; }
        public string CurrST2IsPlanned { get; set; }
        public string PrevST2IsPlanned { get; set; }
        public string CurrGT1IsForced { get; set; }
        public string PrevGT1IsForced { get; set; }
        public string CurrGT2IsForced { get; set; }
        public string PrevGT2IsForced { get; set; }
        public string CurrGT3IsForced { get; set; }
        public string PrevGT3IsForced { get; set; }
        public string CurrGT4IsForced { get; set; }
        public string PrevGT4IsForced { get; set; }
        public string CurrST1IsForced { get; set; }
        public string PrevST1IsForced { get; set; }
        public string CurrST2IsForced { get; set; }
        public string PrevST2IsForced { get; set; }
        public string CurrGT1IsOutageDeration { get; set; }
        public string PrevGT1IsOutageDeration { get; set; }
        public string CurrGT2IsOutageDeration { get; set; }
        public string PrevGT2IsOutageDeration { get; set; }
        public string CurrGT3IsOutageDeration { get; set; }
        public string PrevGT3IsOutageDeration { get; set; }
        public string CurrGT4IsOutageDeration { get; set; }
        public string PrevGT4IsOutageDeration { get; set; }
        public string CurrST1IsOutageDeration { get; set; }
        public string PrevST1IsOutageDeration { get; set; }
        public string CurrST2IsOutageDeration { get; set; }
        public string PrevST2IsOutageDeration { get; set; }
        public Nullable<decimal> GT1GDC { get; set; }
        public Nullable<decimal> GT2GDC { get; set; }
        public Nullable<decimal> GT3GDC { get; set; }
        public Nullable<decimal> GT4GDC { get; set; }
        public Nullable<decimal> ST1GDC { get; set; }
        public Nullable<decimal> ST2GDC { get; set; }
        public Nullable<decimal> GT1ReferenceCapacity { get; set; }
        public Nullable<decimal> GT2ReferenceCapacity { get; set; }
        public Nullable<decimal> GT3ReferenceCapacity { get; set; }
        public Nullable<decimal> GT4ReferenceCapacity { get; set; }
        public Nullable<decimal> ST1ReferenceCapacity { get; set; }
        public Nullable<decimal> ST2ReferenceCapacity { get; set; }
        public Nullable<decimal> GT1AmbDeration { get; set; }
        public Nullable<decimal> GT2AmbDeration { get; set; }
        public Nullable<decimal> GT3AmbDeration { get; set; }
        public Nullable<decimal> GT4AmbDeration { get; set; }
        public Nullable<decimal> ST1AmbDeration { get; set; }
        public Nullable<decimal> ST2AmbDeration { get; set; }
        public Nullable<decimal> GT1ForcedDeration { get; set; }
        public Nullable<decimal> GT2ForcedDeration { get; set; }
        public Nullable<decimal> GT3ForcedDeration { get; set; }
        public Nullable<decimal> GT4ForcedDeration { get; set; }
        public Nullable<decimal> ST1ForcedDeration { get; set; }
        public Nullable<decimal> ST2ForcedDeration { get; set; }
        public Nullable<decimal> GT1PlannedDeration { get; set; }
        public Nullable<decimal> GT2PlannedDeration { get; set; }
        public Nullable<decimal> GT3PlannedDeration { get; set; }
        public Nullable<decimal> GT4PlannedDeration { get; set; }
        public Nullable<decimal> ST1PlannedDeration { get; set; }
        public Nullable<decimal> ST2PlannedDeration { get; set; }
        public Nullable<decimal> GT1PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT2PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT3PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT4PlannedOutageHrs { get; set; }
        public Nullable<decimal> ST1PlannedOutageHrs { get; set; }
        public Nullable<decimal> ST2PlannedOutageHrs { get; set; }
        public Nullable<decimal> GT1UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT2UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT3UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT4UnplannedOutageHrs { get; set; }
        public Nullable<decimal> ST1UnplannedOutageHrs { get; set; }
        public Nullable<decimal> ST2UnplannedOutageHrs { get; set; }
        public Nullable<decimal> GT1PlannedRampHrs { get; set; }
        public Nullable<decimal> GT2PlannedRampHrs { get; set; }
        public Nullable<decimal> GT3PlannedRampHrs { get; set; }
        public Nullable<decimal> GT4PlannedRampHrs { get; set; }
        public Nullable<decimal> ST1PlannedRampHrs { get; set; }
        public Nullable<decimal> ST2PlannedRampHrs { get; set; }
        public Nullable<decimal> GT1ForcedRampHrs { get; set; }
        public Nullable<decimal> GT2ForcedRampHrs { get; set; }
        public Nullable<decimal> GT3ForcedRampHrs { get; set; }
        public Nullable<decimal> GT4ForcedRampHrs { get; set; }
        public Nullable<decimal> ST1ForcedRampHrs { get; set; }
        public Nullable<decimal> ST2ForcedRampHrs { get; set; }
        public Nullable<decimal> GT1UnplannedDerationHrs { get; set; }
        public Nullable<decimal> GT2UnplannedDerationHrs { get; set; }
        public Nullable<decimal> GT3UnplannedDerationHrs { get; set; }
        public Nullable<decimal> GT4UnplannedDerationHrs { get; set; }
        public Nullable<decimal> ST1UnplannedDerationHrs { get; set; }
        public Nullable<decimal> ST2UnplannedDerationHrs { get; set; }
        public Nullable<decimal> GT1PlannedDerationHrs { get; set; }
        public Nullable<decimal> GT2PlannedDerationHrs { get; set; }
        public Nullable<decimal> GT3PlannedDerationHrs { get; set; }
        public Nullable<decimal> GT4PlannedDerationHrs { get; set; }
        public Nullable<decimal> ST1PlannedDerationHrs { get; set; }
        public Nullable<decimal> ST2PlannedDerationHrs { get; set; }
        public Nullable<decimal> GT1LDCOutageHrs { get; set; }
        public Nullable<decimal> GT2LDCOutageHrs { get; set; }
        public Nullable<decimal> GT3LDCOutageHrs { get; set; }
        public Nullable<decimal> GT4LDCOutageHrs { get; set; }
        public Nullable<decimal> ST1LDCOutageHrs { get; set; }
        public Nullable<decimal> ST2LDCOutageHrs { get; set; }
        public Nullable<decimal> GT1StandbyHrs { get; set; }
        public Nullable<decimal> GT2StandbyHrs { get; set; }
        public Nullable<decimal> GT3StandbyHrs { get; set; }
        public Nullable<decimal> GT4StandbyHrs { get; set; }
        public Nullable<decimal> ST1StandbyHrs { get; set; }
        public Nullable<decimal> ST2StandbyHrs { get; set; }
    }
}
