//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTHourlySitewiseKPC1
    {
        public string SiteId { get; set; }
        public System.DateTime RdgDateTime { get; set; }
        public Nullable<decimal> GT1ActualDispatchMW { get; set; }
        public Nullable<decimal> GT2ActualDispatchMW { get; set; }
        public Nullable<decimal> GT3ActualDispatchMW { get; set; }
        public Nullable<decimal> GT4ActualDispatchMW { get; set; }
        public Nullable<decimal> ST1ActualDispatchMW { get; set; }
        public Nullable<decimal> ST2ActualDispatchMW { get; set; }
        public string GT1IsPlanned { get; set; }
        public string GT2IsPlanned { get; set; }
        public string GT3IsPlanned { get; set; }
        public string GT4IsPlanned { get; set; }
        public string ST1IsPlanned { get; set; }
        public string ST2IsPlanned { get; set; }
        public string GT1IsForced { get; set; }
        public string GT2IsForced { get; set; }
        public string GT3IsForced { get; set; }
        public string GT4IsForced { get; set; }
        public string ST1IsForced { get; set; }
        public string ST2IsForced { get; set; }
        public string GT1IsOutageDeration { get; set; }
        public string GT2IsOutageDeration { get; set; }
        public string GT3IsOutageDeration { get; set; }
        public string GT4IsOutageDeration { get; set; }
        public string ST1IsOutageDeration { get; set; }
        public string ST2IsOutageDeration { get; set; }
    }
}
