//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTHourlySitewiseKPC3
    {
        public string SiteId { get; set; }
        public System.DateTime RdgDateTime { get; set; }
        public Nullable<decimal> GT1ActualDispatchMW { get; set; }
        public Nullable<decimal> GT2ActualDispatchMW { get; set; }
        public Nullable<decimal> GT3ActualDispatchMW { get; set; }
        public Nullable<decimal> GT4ActualDispatchMW { get; set; }
        public Nullable<decimal> ST1ActualDispatchMW { get; set; }
        public Nullable<decimal> ST2ActualDispatchMW { get; set; }
        public string GT1IsPlanned { get; set; }
        public string GT2IsPlanned { get; set; }
        public string GT3IsPlanned { get; set; }
        public string GT4IsPlanned { get; set; }
        public string ST1IsPlanned { get; set; }
        public string ST2IsPlanned { get; set; }
        public string GT1IsForced { get; set; }
        public string GT2IsForced { get; set; }
        public string GT3IsForced { get; set; }
        public string GT4IsForced { get; set; }
        public string ST1IsForced { get; set; }
        public string ST2IsForced { get; set; }
        public string GT1IsOutageDeration { get; set; }
        public string GT2IsOutageDeration { get; set; }
        public string GT3IsOutageDeration { get; set; }
        public string GT4IsOutageDeration { get; set; }
        public string ST1IsOutageDeration { get; set; }
        public string ST2IsOutageDeration { get; set; }
        public Nullable<decimal> GT1GDC { get; set; }
        public Nullable<decimal> GT2GDC { get; set; }
        public Nullable<decimal> GT3GDC { get; set; }
        public Nullable<decimal> GT4GDC { get; set; }
        public Nullable<decimal> ST1GDC { get; set; }
        public Nullable<decimal> ST2GDC { get; set; }
        public string GT1IsLDC { get; set; }
        public string GT2IsLDC { get; set; }
        public string GT3IsLDC { get; set; }
        public string GT4IsLDC { get; set; }
        public string ST1IsLDC { get; set; }
        public string ST2IsLDC { get; set; }
        public string GT1IsGas { get; set; }
        public string GT2IsGas { get; set; }
        public string GT3IsGas { get; set; }
        public string GT4IsGas { get; set; }
        public string ST1IsGas { get; set; }
        public string ST2IsGas { get; set; }
        public Nullable<decimal> GT1ReferenceCapacity { get; set; }
        public Nullable<decimal> GT2ReferenceCapacity { get; set; }
        public Nullable<decimal> GT3ReferenceCapacity { get; set; }
        public Nullable<decimal> GT4ReferenceCapacity { get; set; }
        public Nullable<decimal> ST1ReferenceCapacity { get; set; }
        public Nullable<decimal> ST2ReferenceCapacity { get; set; }
        public Nullable<decimal> GT1AmbDeration { get; set; }
        public Nullable<decimal> GT2AmbDeration { get; set; }
        public Nullable<decimal> GT3AmbDeration { get; set; }
        public Nullable<decimal> GT4AmbDeration { get; set; }
        public Nullable<decimal> ST1AmbDeration { get; set; }
        public Nullable<decimal> ST2AmbDeration { get; set; }
        public Nullable<decimal> GT1ForcedDeration { get; set; }
        public Nullable<decimal> GT2ForcedDeration { get; set; }
        public Nullable<decimal> GT3ForcedDeration { get; set; }
        public Nullable<decimal> GT4ForcedDeration { get; set; }
        public Nullable<decimal> ST1ForcedDeration { get; set; }
        public Nullable<decimal> ST2ForcedDeration { get; set; }
        public Nullable<decimal> GT1PlannedDeration { get; set; }
        public Nullable<decimal> GT2PlannedDeration { get; set; }
        public Nullable<decimal> GT3PlannedDeration { get; set; }
        public Nullable<decimal> GT4PlannedDeration { get; set; }
        public Nullable<decimal> ST1PlannedDeration { get; set; }
        public Nullable<decimal> ST2PlannedDeration { get; set; }
        public string GT1StartupRampId { get; set; }
        public string GT2StartupRampId { get; set; }
        public string GT3StartupRampId { get; set; }
        public string GT4StartupRampId { get; set; }
        public string ST1StartupRampId { get; set; }
        public string ST2StartupRampId { get; set; }
    }
}
