//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTDailySitewiseKPCFinal
    {
        public Nullable<long> Id { get; set; }
        public string SiteId { get; set; }
        public Nullable<System.DateTime> theDay { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<decimal> PlannedOutageHrs { get; set; }
        public Nullable<decimal> UnplannedOutageHrs { get; set; }
        public Nullable<decimal> AvailabilityPercent { get; set; }
        public Nullable<decimal> EUDH { get; set; }
        public Nullable<decimal> EPDH { get; set; }
        public Nullable<decimal> LDCOutageHrs { get; set; }
        public Nullable<decimal> StandbyHrs { get; set; }
        public Nullable<decimal> ELRExclGrid { get; set; }
    }
}
