//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRPTHourlySitewiseKPC4
    {
        public string SiteId { get; set; }
        public System.DateTime CurrRdgDateTime { get; set; }
        public Nullable<System.DateTime> PrevRdgDateTime { get; set; }
        public Nullable<decimal> DaysDifference { get; set; }
        public Nullable<decimal> GT1ActualDispatchMW { get; set; }
        public Nullable<decimal> GT2ActualDispatchMW { get; set; }
        public Nullable<decimal> GT3ActualDispatchMW { get; set; }
        public Nullable<decimal> GT4ActualDispatchMW { get; set; }
        public Nullable<decimal> ST1ActualDispatchMW { get; set; }
        public Nullable<decimal> ST2ActualDispatchMW { get; set; }
        public string CurrGT1IsPlanned { get; set; }
        public string PrevGT1IsPlanned { get; set; }
        public string CurrGT2IsPlanned { get; set; }
        public string PrevGT2IsPlanned { get; set; }
        public string CurrGT3IsPlanned { get; set; }
        public string PrevGT3IsPlanned { get; set; }
        public string CurrGT4IsPlanned { get; set; }
        public string PrevGT4IsPlanned { get; set; }
        public string CurrST1IsPlanned { get; set; }
        public string PrevST1IsPlanned { get; set; }
        public string CurrST2IsPlanned { get; set; }
        public string PrevST2IsPlanned { get; set; }
        public string CurrGT1IsOutageDeration { get; set; }
        public string PrevGT1IsOutageDeration { get; set; }
        public string CurrGT2IsOutageDeration { get; set; }
        public string PrevGT2IsOutageDeration { get; set; }
        public string CurrGT3IsOutageDeration { get; set; }
        public string PrevGT3IsOutageDeration { get; set; }
        public string CurrGT4IsOutageDeration { get; set; }
        public string PrevGT4IsOutageDeration { get; set; }
        public string CurrST1IsOutageDeration { get; set; }
        public string PrevST1IsOutageDeration { get; set; }
        public string CurrST2IsOutageDeration { get; set; }
        public string PrevST2IsOutageDeration { get; set; }
        public string CurrGT1IsForced { get; set; }
        public string PrevGT1IsForced { get; set; }
        public string CurrGT2IsForced { get; set; }
        public string PrevGT2IsForced { get; set; }
        public string CurrGT3IsForced { get; set; }
        public string PrevGT3IsForced { get; set; }
        public string CurrGT4IsForced { get; set; }
        public string PrevGT4IsForced { get; set; }
        public string CurrST1IsForced { get; set; }
        public string PrevST1IsForced { get; set; }
        public string CurrST2IsForced { get; set; }
        public string PrevST2IsForced { get; set; }
        public string CurrGT1StartupRampId { get; set; }
        public string PrevGT1StartupRampId { get; set; }
        public string CurrGT2StartupRampId { get; set; }
        public string PrevGT2StartupRampId { get; set; }
        public string CurrGT3StartupRampId { get; set; }
        public string PrevGT3StartupRampId { get; set; }
        public string CurrGT4StartupRampId { get; set; }
        public string PrevGT4StartupRampId { get; set; }
        public string CurrST1StartupRampId { get; set; }
        public string PrevST1StartupRampId { get; set; }
        public string CurrST2StartupRampId { get; set; }
        public string PrevST2StartupRampId { get; set; }
        public string CurrGT1IsGas { get; set; }
        public string PrevGT1IsGas { get; set; }
        public string CurrGT2IsGas { get; set; }
        public string PrevGT2IsGas { get; set; }
        public string CurrGT3IsGas { get; set; }
        public string PrevGT3IsGas { get; set; }
        public string CurrGT4IsGas { get; set; }
        public string PrevGT4IsGas { get; set; }
        public string CurrST1IsGas { get; set; }
        public string PrevST1IsGas { get; set; }
        public string CurrST2IsGas { get; set; }
        public string PrevST2IsGas { get; set; }
        public string CurrGT1IsLDC { get; set; }
        public string PrevGT1IsLDC { get; set; }
        public string CurrGT2IsLDC { get; set; }
        public string PrevGT2IsLDC { get; set; }
        public string CurrGT3IsLDC { get; set; }
        public string PrevGT3IsLDC { get; set; }
        public string CurrGT4IsLDC { get; set; }
        public string PrevGT4IsLDC { get; set; }
        public string CurrST1IsLDC { get; set; }
        public string PrevST1IsLDC { get; set; }
        public string CurrST2IsLDC { get; set; }
        public string PrevST2IsLDC { get; set; }
        public Nullable<decimal> GT1GDC { get; set; }
        public Nullable<decimal> GT2GDC { get; set; }
        public Nullable<decimal> GT3GDC { get; set; }
        public Nullable<decimal> GT4GDC { get; set; }
        public Nullable<decimal> ST1GDC { get; set; }
        public Nullable<decimal> ST2GDC { get; set; }
        public string GT1IsLDC { get; set; }
        public string GT2IsLDC { get; set; }
        public string GT3IsLDC { get; set; }
        public string GT4IsLDC { get; set; }
        public string ST1IsLDC { get; set; }
        public string ST2IsLDC { get; set; }
        public string GT1IsGas { get; set; }
        public string GT2IsGas { get; set; }
        public string GT3IsGas { get; set; }
        public string GT4IsGas { get; set; }
        public string ST1IsGas { get; set; }
        public string ST2IsGas { get; set; }
        public Nullable<decimal> GT1AmbDeration { get; set; }
        public Nullable<decimal> GT2AmbDeration { get; set; }
        public Nullable<decimal> GT3AmbDeration { get; set; }
        public Nullable<decimal> GT4AmbDeration { get; set; }
        public Nullable<decimal> ST1AmbDeration { get; set; }
        public Nullable<decimal> ST2AmbDeration { get; set; }
        public Nullable<decimal> GT1ForcedDeration { get; set; }
        public Nullable<decimal> GT2ForcedDeration { get; set; }
        public Nullable<decimal> GT3ForcedDeration { get; set; }
        public Nullable<decimal> GT4ForcedDeration { get; set; }
        public Nullable<decimal> ST1ForcedDeration { get; set; }
        public Nullable<decimal> ST2ForcedDeration { get; set; }
        public Nullable<decimal> GT1PlannedDeration { get; set; }
        public Nullable<decimal> GT2PlannedDeration { get; set; }
        public Nullable<decimal> GT3PlannedDeration { get; set; }
        public Nullable<decimal> GT4PlannedDeration { get; set; }
        public Nullable<decimal> ST1PlannedDeration { get; set; }
        public Nullable<decimal> ST2PlannedDeration { get; set; }
        public Nullable<decimal> GT1ReferenceCapacity { get; set; }
        public Nullable<decimal> GT2ReferenceCapacity { get; set; }
        public Nullable<decimal> GT3ReferenceCapacity { get; set; }
        public Nullable<decimal> GT4ReferenceCapacity { get; set; }
        public Nullable<decimal> ST1ReferenceCapacity { get; set; }
        public Nullable<decimal> ST2ReferenceCapacity { get; set; }
    }
}
