//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerationLogBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class xEmailReminderRecipient
    {
        public int ID { get; set; }
        public string SiteID { get; set; }
        public Nullable<int> ReminderNo { get; set; }
        public string ToRecipients { get; set; }
        public string CCRecipients { get; set; }
        public Nullable<System.DateTime> RedgDateTime { get; set; }
    
        public virtual SitesMaster SitesMaster { get; set; }
        public virtual SitesMaster SitesMaster1 { get; set; }
    }
}
